import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Home/Footer";
import ToasterProvider from "@/components/ToasterProvider";
import getCurrentUser from "./actions/getCurrentUser";
import Navbar from "@/components/Home/Navbar/Navbar";
import { User } from "@/const";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Earninto",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  // console.log(currentUser, "Shouting from layout");

  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <Navbar currentUser={currentUser?.data} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
